#!/usr/bin/env bash
# One-shot system setup for g2-studio VR sessions. Idempotent; run:
#
#     sudo scripts/setup-system.sh
#
# Everything session-scoped (clocks, C-states, EPP, display dip) is applied
# and reverted by `python3 -m core.steamvr {start|stop}` at runtime — but
# those need a few pieces of root-owned system state, which this script
# installs, prints, and verifies:
#
#   1. /etc/sudoers.d/g2-studio — scoped NOPASSWD grants (exact commands
#      only, no broad root): nvidia-smi clock/power pinning, cpupower
#      governor + idle-state control, setcap for vrserver/monado-service,
#      trace-cmd for the kernel spike tracer. visudo-validated before install.
#   2. /etc/security/limits.d/99-g2-vr-rtprio.conf — RLIMIT_RTPRIO for the
#      login user so vrserver's 1 kHz pose threads can take SCHED_FIFO even
#      when a Steam update wipes the setcap (needs one re-login).
#   3. /usr/lib/linux-tools/$(uname -r) symlink — Ubuntu's /usr/bin/cpupower
#      is a wrapper that dispatches on `uname -r` and, on a custom kernel
#      with no matching linux-tools package, prints a warning and EXITS 0
#      WITHOUT DOING ANYTHING (this silently no-opped governor pinning for
#      weeks). cpupower's freq/idle ops are plain sysfs writes and any
#      installed version works on any running kernel, so a symlink to the
#      newest installed version repairs the wrapper. Re-run after kernel
#      upgrades.
set -euo pipefail

[ "$(id -u)" = 0 ] || { echo "run with sudo: sudo $0" >&2; exit 1; }
G2_USER=${SUDO_USER:-}
[ -n "$G2_USER" ] && [ "$G2_USER" != root ] \
    || { echo "run via sudo from your login user (SUDO_USER unset)" >&2; exit 1; }
REPO=$(cd "$(dirname "$0")/.." && pwd)

echo "== g2-studio system setup (user: $G2_USER, repo: $REPO)"

# --- 1. scoped sudoers grants -------------------------------------------------
VRSERVER="/home/$G2_USER/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrserver"
MONADO_SVC="/home/$G2_USER/.local/bin/monado-service"
SUDOERS=/etc/sudoers.d/g2-studio
TMP=$(mktemp)
cat > "$TMP" <<EOF
# g2-studio scoped grants — generated by scripts/setup-system.sh, safe to re-run.
# Exact commands only; nothing here grants a shell or broad root.
$G2_USER ALL=(root) NOPASSWD: /usr/bin/nvidia-smi -pm *, /usr/bin/nvidia-smi -pl *, /usr/bin/nvidia-smi -lgc *, /usr/bin/nvidia-smi -lmc *, /usr/bin/nvidia-smi -rgc, /usr/bin/nvidia-smi -rmc, /usr/bin/nvidia-smi -c *
$G2_USER ALL=(root) NOPASSWD: /usr/bin/cpupower frequency-set *, /usr/bin/cpupower idle-set *
$G2_USER ALL=(root) NOPASSWD: /usr/sbin/setcap cap_sys_nice+ep $VRSERVER
$G2_USER ALL=(root) NOPASSWD: /usr/sbin/setcap cap_sys_nice+ep $MONADO_SVC
$G2_USER ALL=(root) NOPASSWD: /usr/bin/trace-cmd
EOF
visudo -c -q -f "$TMP" || { echo "ERR: generated sudoers failed validation" >&2; rm -f "$TMP"; exit 1; }
install -m 0440 -o root -g root "$TMP" "$SUDOERS"; rm -f "$TMP"
echo "   installed $SUDOERS"
for f in /etc/sudoers.d/g2ctl-vrserver /etc/sudoers.d/g2ctl-trace /etc/sudoers.d/g2ctl-cstates; do
    [ -e "$f" ] && echo "   note: legacy $f also present (harmless duplicate; remove at will)"
done

# --- 2. RT-priority limit -----------------------------------------------------
LIMITS=/etc/security/limits.d/99-g2-vr-rtprio.conf
sed "s/^mrwhite0racle /$G2_USER /" "$REPO/system/99-g2-vr-rtprio.conf" > "$LIMITS"
chmod 0644 "$LIMITS"
echo "   installed $LIMITS (takes effect after the next login)"

# --- 3. cpupower wrapper repair for custom kernels ----------------------------
KVER=$(uname -r)
if [ ! -e "/usr/lib/linux-tools/$KVER" ]; then
    LATEST=$(ls -1v /usr/lib/linux-tools/ 2>/dev/null | tail -1 || true)
    if [ -n "$LATEST" ]; then
        ln -s "$LATEST" "/usr/lib/linux-tools/$KVER"
        echo "   linked /usr/lib/linux-tools/$KVER -> $LATEST"
    else
        echo "   WARN: no linux-tools installed at all — apt install linux-tools-generic, then re-run"
    fi
else
    echo "   /usr/lib/linux-tools/$KVER already resolves"
fi

# --- verify -------------------------------------------------------------------
echo "== verify"
/usr/bin/cpupower idle-set -D 200 >/dev/null \
    && grep -qx 1 /sys/devices/system/cpu/cpu0/cpuidle/state4/disable \
    && echo "   cpupower idle-set: OK (deep C-states toggled)" \
    || echo "   cpupower idle-set: FAILED — check step 3 output"
/usr/bin/cpupower idle-set -E >/dev/null || true
if [ -x "$VRSERVER" ]; then
    setcap cap_sys_nice+ep "$VRSERVER" && echo "   vrserver setcap: OK ($(getcap "$VRSERVER"))"
else
    echo "   vrserver not found at $VRSERVER (install SteamVR, re-run or let the launcher apply it)"
fi
echo "== done. One re-login is needed once for the rtprio limit."
